name: Amfibi_App
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.8.0
  firebase_storage: ^11.2.5
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  shared_preferences: ^2.1.0
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^1.1.6
  simple_shadow: ^0.2.0
  flutter_spinkit: ^5.1.0
  iconsax_flutter: ^1.0.0
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/